#!/usr/bin/env python3

import re
import sys

sum=0

for line in sys.stdin.readlines():
    if matches := re.match(r"^Game (\d+):\s+(.+)$", line):
        game_id = int(matches[1])
        grabs = re.split(r"[,;]\s*", matches[2])
        max_counts = {}
        for grab in grabs:
            (count, color) = grab.split()
            max_counts[color] = max(int(count), max_counts.get(color, 0))

        power = (
            max_counts.get("red", 1) *
            max_counts.get("green", 1) *
            max_counts.get("blue", 1)
        )
        sum += power

print(sum)
    
